vim.keymap.set("", "<plug>(IndentTextobjectSelectInner)", function()
	require("indent-textobject").select_inner()
end)
vim.keymap.set("", "<plug>(IndentTextobjectSelectAround)", function()
	require("indent-textobject").select_around()
end)

vim.keymap.set("", "<plug>(IndentTextobjectGotoInnerTop)", function()
	require("indent-textobject").goto_inner_top()
end)
vim.keymap.set("", "<plug>(IndentTextobjectGotoInnerBot)", function()
	require("indent-textobject").goto_inner_bot()
end)

vim.keymap.set("", "<plug>(IndentTextobjectGotoAroundTop)", function()
	require("indent-textobject").goto_around_top()
end)
vim.keymap.set("", "<plug>(IndentTextobjectGotoAroundBot)", function()
	require("indent-textobject").goto_around_bot()
end)
